# Generated by Django 5.0.6 on 2024-06-12 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_pay_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='product',
        ),
        migrations.AddField(
            model_name='pay',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.cart'),
            preserve_default=False,
        ),
    ]
