# Generated by Django 5.0.6 on 2024-06-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_pay_product_pay_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='pay',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Phone number'),
            preserve_default=False,
        ),
    ]
