# Generated by Django 5.0.6 on 2024-06-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_contactus_alter_pay_email_alter_pay_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='address',
            field=models.TextField(default=1, verbose_name='Address'),
            preserve_default=False,
        ),
    ]
