# Generated by Django 5.0.6 on 2024-06-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_contactus_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='address',
            field=models.TextField(default=1, verbose_name='Address'),
            preserve_default=False,
        ),
    ]
