# Generated by Django 5.0.6 on 2024-06-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_pay_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('static_text', models.CharField(max_length=50, verbose_name='HomeInfo')),
                ('dinamic_text1', models.CharField(max_length=50, verbose_name='HomeInfo text 1')),
                ('dinamic_text2', models.CharField(max_length=50, verbose_name='HomeInfo text 2')),
                ('dinamic_text3', models.CharField(max_length=50, verbose_name='HomeInfo text 3')),
                ('about', models.TextField(verbose_name='HomeInfo')),
                ('button_name', models.CharField(max_length=50, verbose_name='HomeInfo')),
            ],
        ),
        migrations.RemoveField(
            model_name='pay',
            name='address',
        ),
    ]
