# Generated by Django 5.0.6 on 2024-06-13 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_usermessage_delete_homeinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product_hy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='name_hy',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.TextField(null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_hy',
            field=models.TextField(null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.TextField(null=True, verbose_name='Product name'),
        ),
    ]
